on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: kkkykin/ScoopActions@init-by-repo-dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCOOP_GH_TOKEN: ${{ secrets.VISIT_BUILD_REPO }}
          SKIP_UPDATED: 1
